#!/usr/bin/env node
/**
 * Builder dei design tokens.
 *
 * Trasforma i JSON in `tokens/` in:
 *   dist/tokens.css   — :root con custom properties OKLCH + semantici via light-dark()
 *   dist/tokens.js    — esporta `tokens` per consumo JS (canvas, sparkline, ecc.)
 *
 * Zero dipendenze npm (volutamente). Style Dictionary può essere introdotto in
 * fase più avanzata se servono target multipli (iOS Compose Figma); per ora
 * un builder minimale ci permette di restare snelli.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const TOKENS_DIR = join(HERE, 'tokens');
const DIST_DIR = join(HERE, 'dist');

const FILES = ['color', 'space', 'typography', 'elevation', 'radius', 'motion', 'z-index', 'breakpoints'];

function loadAll() {
  /** @type {Record<string, unknown>} */
  const all = {};
  for (const f of FILES) {
    const raw = readFileSync(join(TOKENS_DIR, `${f}.json`), 'utf8');
    all[f] = JSON.parse(raw);
  }
  return all;
}

/** Risolve placeholder {primitives.indigo.500} → "oklch(...)" */
function resolveRef(value, root) {
  if (typeof value !== 'string') return value;
  const m = /^\{([\w.-]+)\}$/.exec(value);
  if (!m) return value;
  const path = m[1].split('.');
  let cur = root.color;
  for (const k of path) {
    if (cur === undefined) return value;
    cur = cur[k];
  }
  return typeof cur === 'string' ? cur : value;
}

function kebab(s) {
  return s.replace(/_/g, '-').toLowerCase();
}

/** Appiattisce un sub-tree in coppie [varName, value], saltando i $comment. */
function flatten(prefix, obj, out, root) {
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith('$')) continue;
    const next = prefix ? `${prefix}-${kebab(k)}` : kebab(k);
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      // semantico { light, dark }?
      if ('light' in v && 'dark' in v) {
        const lt = resolveRef(v.light, root);
        const dk = resolveRef(v.dark, root);
        out.push([`--${next}`, `light-dark(${lt}, ${dk})`]);
      } else {
        flatten(next, v, out, root);
      }
    } else {
      out.push([`--${next}`, String(v)]);
    }
  }
}

function build() {
  const all = loadAll();
  /** @type {[string, string][]} */
  const lines = [];

  // colori primitives + semantici
  flatten('color', all.color.primitives, lines, all);
  flatten('color', all.color.semantic, lines, all);
  // altri token (space, typography, …)
  flatten('space', all.space.space, lines, all);
  flatten('font', all.typography.font, lines, all);
  flatten('elevation', all.elevation.elevation, lines, all);
  flatten('radius', all.radius.radius, lines, all);
  flatten('motion', all.motion.motion, lines, all);
  flatten('z', all['z-index'].z, lines, all);
  flatten('container', all.breakpoints.container, lines, all);

  // CSS output — inserito in @layer tokens
  const cssBody = lines.map(([k, v]) => `  ${k}: ${v};`).join('\n');
  const css = `/* AUTO-GENERATED by tokens.config.mjs — DO NOT EDIT BY HAND */\n@layer tokens {\n  :root {\n    color-scheme: light dark;\n${cssBody}\n  }\n}\n`;

  // JS output (oggetto piatto)
  const jsObj = Object.fromEntries(lines.map(([k, v]) => [k.replace(/^--/, ''), v]));
  const js = `// AUTO-GENERATED by tokens.config.mjs — DO NOT EDIT BY HAND\nexport const tokens = ${JSON.stringify(jsObj, null, 2)};\n`;

  mkdirSync(DIST_DIR, { recursive: true });
  writeFileSync(join(DIST_DIR, 'tokens.css'), css, 'utf8');
  writeFileSync(join(DIST_DIR, 'tokens.js'), js, 'utf8');
  writeFileSync(
    join(DIST_DIR, 'tokens.d.ts'),
    `export declare const tokens: Record<string, string>;\n`,
    'utf8',
  );

  console.info(`✓ design-system: wrote ${lines.length} tokens to dist/tokens.css`);
}

build();
