/**
 * Quality Gate pre-import — detect "workflow merdosi" generated by Liara.
 *
 * Filosofia: l'AI può produrre output SINTATTICAMENTE valido (Zod-passes)
 * ma SEMANTICAMENTE rotto (reference circolari, mock URL, dead-end branch,
 * placeholder fake che non funzioneranno mai a runtime). Questo gate
 * impedisce che un workflow non-eseguibile venga importato come "completo"
 * — preserva la promessa "premi Importa → funziona".
 *
 * 5 categorie di rules:
 *   1. CIRCULAR — nodo X.config referencia `{{$node.Y.json…}}` MA X precede
 *      Y nel DAG (Y non è ancora eseguito quando X parte).
 *   2. MOCK_PLACEHOLDER — config field contiene example.com, localhost,
 *      noreply@example.com, smtp.example.com, etc → non funzionerà mai.
 *   3. SWITCH_NO_DEFAULT — logic_switch senza defaultCase → documento "altro"
 *      diventa orphan a runtime.
 *   4. DEAD_END — branch interno termina senza output (non-leaf, non-sink).
 *      Es. logic_if → slack ma niente else → metà documenti spariscono.
 *   5. ORPHAN_TRIGGER — trigger senza edges in uscita → mai eseguibile.
 *
 * Severity:
 *   - critical → throw AiScaffoldError, workflow REJECTED + salvato come
 *     "esempio negativo" per training futuro
 *   - medium → notes warning all'utente, importabile ma con avviso
 *   - info → solo log server-side (no UI noise)
 *
 * Pure function: nessun side effect, testabile a moduli. Estratta da
 * singleshot.service.ts per modularità (NO MONOLITI rule).
 */

import { logger } from '@/lib/logger.js';
import {
  isArrayProducer,
  isScalarConsumer,
  isAggregator,
  isLoopBodyPassthrough,
} from '@/services/ai-scaffold/node-shape.js';
import { detectCodeLanguage, LANG_FOR_CODE_NODE } from '@/services/ai-scaffold/code-lang.js';
import { checkEspressioneNuda } from '@/services/ai-scaffold/rule-espressione-nuda.js';
import { checkNienteDaElaborare } from '@/services/ai-scaffold/rule-niente-da-elaborare.js';
import { checkListaCheNonArriva } from '@/services/ai-scaffold/rule-lista-che-non-arriva.js';
import { checkRegoleCondizione } from '@/services/ai-scaffold/rule-regole-condizione.js';
import { runSemanticRules } from '@/services/ai-scaffold/semantic-rules.js';

export type QualitySeverity = 'critical' | 'medium' | 'info';
export type QualityCode =
  | 'CIRCULAR_REFERENCE'
  | 'MOCK_PLACEHOLDER'
  | 'SWITCH_NO_DEFAULT'
  | 'DEAD_END_BRANCH'
  | 'ORPHAN_TRIGGER'
  | 'DUPLICATE_NODES'
  | 'SUSPICIOUS_RESOURCE_ID'
  | 'SWITCH_INVALID_CASE_KEY'
  | 'AGGREGATION_INSIDE_LOOP'
  | 'ARRAY_TO_SCALAR_WITHOUT_LOOP'
  | 'FAN_IN_WITHOUT_MERGE'
  | 'DB_TABLE_NOT_IN_SCHEMA'
  | 'DB_COLUMN_NOT_IN_SCHEMA'
  | 'CODE_NODE_LANG_MISMATCH'
  | 'OBSOLETE_MODEL'
  // ── Semantica (semantic-rules.ts + semantic-rules-config.ts) ───────────
  | 'ERROR_BRANCH_INVERTED'
  | 'ERROR_HANDLER_NO_SINK'
  | 'LOOKUP_WITHOUT_BRANCH'
  | 'TRIGGER_WITHOUT_ACTION'
  | 'AUDIT_NOT_TERMINAL'
  | 'SENSITIVE_HARDCODED'
  // ── Espressioni (rule-espressione-nuda.ts) ─────────────────────────────
  | 'ESPRESSIONE_NON_RISOLVIBILE'
  // ── Flusso senza materia (rule-niente-da-elaborare.ts) ─────────────────
  | 'NIENTE_DA_ELABORARE'
  // ── Condizioni che non si valutano (rule-regole-condizione.ts) ─────────
  | 'REGOLE_CONDIZIONE_MALFORMATE'
  // ── Un filtro su ciò che lista non è (rule-lista-che-non-arriva.ts) ────
  | 'LISTA_CHE_NON_ARRIVA';

export interface QualityIssue {
  severity: QualitySeverity;
  code: QualityCode;
  nodeId?: string;
  field?: string;
  message: string;
}

export interface QualityGateInput {
  nodes: {
    id: string;
    defId: string;
    config: Record<string, unknown>;
  }[];
  edges: {
    from: string;
    to: string;
  }[];
  /**
   * Tenant database catalog (passed by singleshot.service). Used by
   * `DB_TABLE_NOT_IN_SCHEMA` rule to ensure `db_query`/`db_insert` reference
   * a real table. Optional — when omitted the rule is skipped.
   *
   * `columns` (table name → column names) abilita la rule
   * `DB_COLUMN_NOT_IN_SCHEMA`: verifica che `rowJson`/`whereJson`/`patchJson`
   * di db_insert/update/delete referenzino SOLO colonne esistenti. Quando
   * assente, la sola rule colonna è skippata (table check resta attivo).
   */
  databases?: readonly {
    id: string;
    tables: readonly string[];
    columns?: Readonly<Record<string, readonly string[]>>;
  }[];
}

export interface QualityGateResult {
  ok: boolean;
  issues: QualityIssue[];
  /** True se almeno un issue ha severity 'critical' → reject + save negative. */
  shouldReject: boolean;
}

/**
 * Pattern di placeholder/mock noti — il LLM li mette quando non sa cosa
 * suggerire. A runtime falliscono SEMPRE.
 *
 * Note: NON includiamo `{{secrets.X}}` o `{{$node.Y.json...}}` — quelli
 * sono template engine validi.
 */
const MOCK_PATTERNS: readonly { regex: RegExp; reason: string; suggest?: string }[] = [
  // ── Domini/host fittizi ─────────────────────────────────────────────
  {
    regex: /\bsmtp\.example\.com\b/i,
    reason: 'SMTP host fittizio "smtp.example.com"',
    suggest: 'smtp.gmail.com / smtp.orion.it / il tuo host reale',
  },
  {
    regex: /\bexample\.(com|org|net|io|biz)\b/i,
    reason: 'dominio fittizio "example.*"',
    suggest: 'il tuo dominio reale (es. miosito.com)',
  },
  {
    regex:
      /\b(your|my|company|yourcompany|mycompany|acme|foo|bar|test|demo|sample|miosito|mio-sito|tuosito|tuo-sito|tuodominio|miodominio|nostrosito|nostrodominio|placeholder|esempio)\.(com|org|net|io|biz|local|it|eu)\b/i,
    reason: 'dominio placeholder fittizio (anche miosito/tuosito/tuodominio italiani)',
    suggest: 'il dominio reale o {{secrets.DOMAIN}} / {{secrets.SITE_URL}}',
  },
  {
    regex: /\bcompany\.com\b/i,
    reason: 'dominio fittizio "company.com"',
    suggest: 'il tuo dominio aziendale reale',
  },
  {
    regex: /\b(yourdomain|domain|hostname|server)\.(com|local|tld)\b/i,
    reason: 'host placeholder generico',
    suggest: "l'host reale (es. miosito.com)",
  },
  {
    regex: /\b(localhost|0\.0\.0\.0|127\.0\.0\.1)\b/i,
    reason: 'host loopback (probabilmente non intenzionale)',
    suggest: "l'IP/host pubblico reale",
  },

  // ── Email destinatario / from ──────────────────────────────────────
  {
    regex: /\bnoreply@(?!example\.|test\.|sample\.)[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/i,
    reason: 'email noreply con dominio placeholder',
    suggest: '{{secrets.NOREPLY_EMAIL}} o email aziendale reale',
  },
  {
    regex:
      /\b(management|admin|test|user|info|support|hello|contact|sales|marketing|root)@(?!.*\.)/i,
    reason: 'email destinatario incompleta',
    suggest: 'email completa reale o {{secrets.EMAIL}}',
  },
  {
    regex:
      /\b[A-Za-z0-9._%+-]+@(company|yourcompany|mycompany|acme|foo|bar|test|demo|sample|placeholder)\.[A-Za-z]{2,}\b/i,
    reason: 'email con dominio aziendale placeholder',
    suggest: '{{secrets.EMAIL}} o indirizzo reale',
  },

  // ── Bucket / storage ────────────────────────────────────────────────
  {
    regex:
      /\bs3:\/\/(my-bucket|your-bucket|bucket-name|bucket|test-bucket|sample-bucket|demo-bucket|example-bucket|company-bucket|tenant-bucket|placeholder-bucket)(?:[/-]|$)/i,
    reason: 'S3 bucket placeholder',
    suggest: 's3://nome-bucket-reale-tenant o {{secrets.S3_BUCKET}}',
  },
  {
    regex: /\bgs:\/\/(my-bucket|your-bucket|bucket-name|bucket)\b/i,
    reason: 'GCS bucket placeholder',
    suggest: 'gs://bucket-reale o {{secrets.GCS_BUCKET}}',
  },
  {
    regex: /\b(my-bucket|your-bucket|bucket-name|tenant-bucket|placeholder-bucket)\b/i,
    reason: 'nome bucket placeholder',
    suggest: 'nome bucket reale o {{secrets.BUCKET_NAME}}',
  },

  // ── Credenziali / API key ──────────────────────────────────────────
  {
    regex: /\byour[_-]?api[_-]?key\b/i,
    reason: 'API key placeholder "your-api-key"',
    suggest: '{{secrets.API_KEY}} o key reale',
  },
  {
    regex:
      /\b(your|my|test|sample|demo)[_-]?(token|secret|password|api_?key|access_?key|client_?id|client_?secret)\b/i,
    reason: 'credential placeholder',
    suggest: '{{secrets.X}} con il vero secret',
  },
  {
    regex: /\bsk_(test|live)_(your|placeholder|sample)/i,
    reason: 'Stripe key placeholder',
    suggest: '{{secrets.STRIPE_KEY}}',
  },
  {
    regex: /\bAKIA[A-Z0-9]{16}\b/,
    reason: 'AWS Access Key ID hardcoded (security risk)',
    suggest: '{{secrets.AWS_ACCESS_KEY_ID}}',
  },

  // ── Account/resource ID placeholder ────────────────────────────────
  {
    regex:
      /\b(email|smtp|imap|account|user|db|database|workspace|project|tenant)[_-]?(account[_-]?)?[_-]?[0-9]+\b/i,
    reason: 'ID risorsa placeholder (es. account-1, db-1, user-123)',
    suggest: 'seleziona via dropdown UI (es. email-account-picker / db-picker) o usa il vero ID',
  },
  {
    regex:
      /\b(account|workspace|project|tenant|database|table)[_-]?(name|id)[_-]?(here|placeholder|example|sample)\b/i,
    reason: 'ID risorsa placeholder generico',
    suggest: 'ID reale dal tenant',
  },
  {
    regex: /\bdb[_-]?(opportunities|customers|orders|invoices|leads)\b/i,
    reason: 'database ID placeholder generico ("db_opportunities" non è un vero ID)',
    suggest: "seleziona via db-picker UI o usa l'UUID reale",
  },

  // ── URL/endpoint generici ──────────────────────────────────────────
  {
    regex:
      /\bhttps?:\/\/(api|service|endpoint|server|host)\.(example|company|yourcompany|placeholder)\.(com|org|net)\b/i,
    reason: 'URL endpoint placeholder',
    suggest: 'URL reale del servizio o {{secrets.API_URL}}',
  },
  {
    regex: /\bhttps?:\/\/(api|service|server)\.example\.com/i,
    reason: 'API URL fittizio',
    suggest: 'URL reale del tuo servizio',
  },

  // ── Token literali generici ────────────────────────────────────────
  { regex: /\bxxx+\b/i, reason: 'placeholder generico "xxx…"', suggest: 'valore reale' },
  { regex: /\bTODO\b/, reason: 'placeholder "TODO" non risolto', suggest: 'completa il valore' },
  { regex: /\bFIXME\b/, reason: 'placeholder "FIXME" non risolto', suggest: 'risolvi il valore' },
  {
    regex: /\bplaceholder\b/i,
    reason: 'token literale "placeholder"',
    suggest: 'sostituisci con valore reale',
  },
  { regex: /\bchange[_-]?me\b/i, reason: 'token literale "change_me"', suggest: 'valore reale' },
  {
    regex:
      /\b(your|my|sample|test|example|demo)[_-]?(value|name|id|key|token|url|host|port|password|secret)\b/i,
    reason: 'placeholder generico tipo "your_value"',
    suggest: 'valore reale o {{secrets.X}}',
  },
  {
    regex: /<[A-Z_]{3,}>/,
    reason: 'placeholder angular brackets <NOME_VAR>',
    suggest: 'sostituisci con valore reale o {{espressione}}',
  },
  {
    regex: /\$\{[A-Z_]{3,}\}/,
    reason: 'placeholder shell-style ${NOME_VAR} non risolto',
    suggest: 'usa {{secrets.X}} o {{$node.Y.json}} (FlowForge expression syntax)',
  },
];

/**
 * Estrae i riferimenti `{{$node.X.json…}}` da una stringa config.
 * Ritorna i node ID referenziati (deduplicati).
 */
function extractNodeRefs(value: string): string[] {
  const matches = value.matchAll(/\{\{\s*\$node\.([A-Za-z0-9_-]+)\.json[^}]*\}\}/g);
  const refs = new Set<string>();
  for (const m of matches) {
    if (m[1]) refs.add(m[1]);
  }
  return Array.from(refs);
}

/**
 * BFS per costruire l'insieme degli ancestor di un nodo nel DAG.
 * Ancestor = nodi che vengono ESEGUITI PRIMA di questo nodo.
 * Se X referencia Y, allora Y deve essere ancestor di X.
 */
function buildAncestors(
  nodeId: string,
  edges: readonly { from: string; to: string }[],
): Set<string> {
  const ancestors = new Set<string>();
  const stack: string[] = [];
  for (const e of edges) if (e.to === nodeId) stack.push(e.from);
  while (stack.length > 0) {
    const cur = stack.pop();
    if (!cur || ancestors.has(cur)) continue;
    ancestors.add(cur);
    for (const e of edges) if (e.to === cur) stack.push(e.from);
  }
  return ancestors;
}

/**
 * Rule 1 — Reference circolare: X.config referencia $node.Y MA Y non è
 * ancestor di X nel DAG.
 *
 * Severity: critical (workflow rotto a runtime — Y.json non disponibile).
 */
function checkCircularReferences(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  const nodeIds = new Set(input.nodes.map((n) => n.id));
  for (const node of input.nodes) {
    const ancestors = buildAncestors(node.id, input.edges);
    for (const [field, val] of Object.entries(node.config)) {
      const str = typeof val === 'string' ? val : JSON.stringify(val);
      const refs = extractNodeRefs(str);
      for (const refId of refs) {
        if (!nodeIds.has(refId)) {
          issues.push({
            severity: 'critical',
            code: 'CIRCULAR_REFERENCE',
            nodeId: node.id,
            field,
            message: `Campo "${field}" referencia $node.${refId} ma il nodo "${refId}" non esiste nel workflow.`,
          });
          continue;
        }
        if (refId === node.id) {
          issues.push({
            severity: 'critical',
            code: 'CIRCULAR_REFERENCE',
            nodeId: node.id,
            field,
            message: `Campo "${field}" referencia se stesso ($node.${refId}). Self-reference impossibile.`,
          });
          continue;
        }
        if (!ancestors.has(refId)) {
          issues.push({
            severity: 'critical',
            code: 'CIRCULAR_REFERENCE',
            nodeId: node.id,
            field,
            message: `Campo "${field}" referencia $node.${refId}.json MA "${refId}" non è ancestor di "${node.id}" nel DAG. A runtime, "${refId}" non è ancora eseguito quando "${node.id}" parte → reference vuota.`,
          });
        }
      }
    }
  }
  return issues;
}

/**
 * Rule 2 — Mock placeholder URL/email/bucket nel config.
 *
 * Severity: critical per SMTP/URL/bucket (cliente vede errore immediato),
 * medium per email destinatario.
 */
function checkMockPlaceholders(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  for (const node of input.nodes) {
    for (const [field, val] of Object.entries(node.config)) {
      const str = typeof val === 'string' ? val : JSON.stringify(val);
      for (const { regex, reason, suggest } of MOCK_PATTERNS) {
        if (!regex.test(str)) continue;
        // Severity: SMTP/host/url/bucket/account_id/database/credentials sono critical
        // (workflow rotto al primo run). Email destinatario è medium (utente può capirlo).
        const critical =
          /smtp|url|host|bucket|endpoint|directory|account|database|table|api_?key|token|secret|password|credential|workspace|tenant/i.test(
            field,
          ) || /smtp\.example|my-bucket|your-api-key/i.test(str);
        const suggestion = suggest ? ` → suggerito: ${suggest}` : '';
        issues.push({
          severity: critical ? 'critical' : 'medium',
          code: 'MOCK_PLACEHOLDER',
          nodeId: node.id,
          field,
          message: `Campo "${field}" contiene ${reason}${suggestion}`,
        });
        break; // 1 issue per field è sufficiente
      }
    }
  }
  return issues;
}

/**
 * Rule 3 — logic_switch senza defaultCase / con cases mappate ma key non
 * esauste delle label classifier.
 *
 * Severity: medium — workflow funziona ma documenti "altri" diventano
 * orphan e silentemente droppati.
 */
function checkSwitchDefault(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  for (const node of input.nodes) {
    if (node.defId !== 'logic_switch') continue;
    const casesRaw = node.config.cases;
    const defaultCase = node.config.defaultCase ?? node.config.default;
    if (defaultCase !== undefined && defaultCase !== null && defaultCase !== '') continue;
    const casesObj = typeof casesRaw === 'string' ? safeParseJson(casesRaw) : casesRaw;
    if (casesObj && typeof casesObj === 'object') {
      issues.push({
        severity: 'medium',
        code: 'SWITCH_NO_DEFAULT',
        nodeId: node.id,
        field: 'defaultCase',
        message: `Switch "${node.id}" ha ${Object.keys(casesObj).length.toString()} cases ma nessun defaultCase. Documenti che non matchano nessuna case diventano orphan.`,
      });
    }
  }
  return issues;
}

function safeParseJson(s: string): unknown {
  try {
    return JSON.parse(s);
  } catch {
    return null;
  }
}

/**
 * Rule 8 — Switch invalid case key (workflow-killer 2026-05-31).
 *
 * Il logic_switch executor fa SOLO equality match: `normalize(c.match) === subjectNorm`.
 * Quindi case keys come `"score < 90"`, `"x > 5"`, `"name && active"` NON vengono
 * mai matchate → workflow cade SEMPRE sul fallbackBranch → workflow morto.
 *
 * Detect: pattern operatori `<`, `>`, `<=`, `>=`, `==`, `===`, `!=`, `&&`,
 * `||`, parentesi function-call → critical.
 *
 * Suggerimento: usare `logic_if` con condition rules (vero engine espressione)
 * invece di `logic_switch` (solo enum discreto).
 */
const OPERATOR_IN_CASE_RE = /(<|>|<=|>=|==|===|!=|!==|&&|\|\||\(|\))/;

/**
 * Rule 9 — Aggregation inside loop (workflow-killer 2026-05-31).
 *
 * Pattern errato:
 *   logic_loop → ... → agent_data_analyst (con extraContext "report/riepilogo")
 *                   → action_send_email (con subject "report/summary")
 *
 * Risultato: N report e N email (1 per iteration). Goal voleva 1 sola sintesi
 * post-loop. Pattern corretto: aggregation/email DOPO il loop.
 *
 * Detection euristica:
 *  - Identifica nodi DENTRO il body di un logic_loop (downstream del loop,
 *    upstream del prossimo nodo NON-loop chain)
 *  - Se ci sono `agent_data_analyst`/`agent_summarizer` con extraContext
 *    contenente "report", "riepilogo", "summary", "aggregato", "totale"
 *    → critical (workflow esegue N volte costose AI calls + spam email)
 *  - Se action_send_email con subject contenente le stesse keyword
 *    → critical
 *
 * Severity: critical (impatto economico: N×$$$ + spam email user).
 */
const AGGREGATION_KEYWORDS_RE =
  /(report|riepilogo|riassunto|summary|aggregat|totale|consolidat|sintesi|recap|digest)/i;

function findDownstreamNodes(
  startNodeId: string,
  edges: readonly { from: string; to: string }[],
): Set<string> {
  const out = new Set<string>();
  const stack = [startNodeId];
  while (stack.length > 0) {
    const cur = stack.pop();
    if (!cur) continue;
    for (const e of edges) {
      if (e.from === cur && !out.has(e.to)) {
        out.add(e.to);
        stack.push(e.to);
      }
    }
  }
  return out;
}

function checkAggregationInsideLoop(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  const loopNodes = input.nodes.filter((n) => n.defId === 'logic_loop');
  if (loopNodes.length === 0) return issues;
  for (const loop of loopNodes) {
    // 2026-06-09: skip se strategy=batch — il loop esegue 1 volta sul totale
    // dell'array, l'aggregator downstream è il behavior CORRETTO desiderato.
    // L'auto-fix Layer C imposta automaticamente strategy=batch quando rileva
    // aggregator downstream (vedi auto-fix.ts §2.5).
    const strategy = typeof loop.config.strategy === 'string' ? loop.config.strategy : 'naive';
    if (strategy === 'batch') continue;
    const downstream = findDownstreamNodes(loop.id, input.edges);
    for (const dsId of downstream) {
      const dsNode = input.nodes.find((n) => n.id === dsId);
      if (!dsNode) continue;
      const isAggregator =
        dsNode.defId === 'agent_data_analyst' ||
        dsNode.defId === 'agent_summarizer' ||
        dsNode.defId === 'action_send_email';
      if (!isAggregator) continue;
      const cfgText = JSON.stringify(dsNode.config);
      if (!AGGREGATION_KEYWORDS_RE.test(cfgText)) continue;
      issues.push({
        severity: 'critical',
        code: 'AGGREGATION_INSIDE_LOOP',
        nodeId: dsNode.id,
        message: `Nodo "${dsNode.id}" (${dsNode.defId}) è DOWNSTREAM del logic_loop "${loop.id}" (strategy="${strategy}") e contiene keyword di aggregazione (report/riepilogo/summary). → A runtime verrà eseguito N volte invece di 1 sola sul totale. Inefficiente + costoso + spam. SOLUZIONE: imposta logic_loop strategy="batch" (l'auto-fix lo fa quando rileva aggregator + keyword report) oppure sposta questo nodo DOPO la chiusura del loop.`,
      });
    }
  }
  return issues;
}

function checkSwitchInvalidCaseKey(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  for (const node of input.nodes) {
    if (node.defId !== 'logic_switch') continue;
    const casesRaw = node.config.cases;
    const casesObj = typeof casesRaw === 'string' ? safeParseJson(casesRaw) : casesRaw;
    if (!casesObj || typeof casesObj !== 'object') continue;
    // 2 forme possibili: { "key1": "branch1" } o [{ case: "x", output: "y" }]
    const keys: string[] = [];
    if (Array.isArray(casesObj)) {
      for (const c of casesObj) {
        if (c && typeof c === 'object') {
          const k = (c as Record<string, unknown>).case ?? (c as Record<string, unknown>).match;
          if (typeof k === 'string') keys.push(k);
        }
      }
    } else {
      keys.push(...Object.keys(casesObj));
    }
    const invalid = keys.filter((k) => OPERATOR_IN_CASE_RE.test(k));
    if (invalid.length === 0) continue;
    issues.push({
      severity: 'critical',
      code: 'SWITCH_INVALID_CASE_KEY',
      nodeId: node.id,
      field: 'cases',
      message: `Switch "${node.id}" ha case keys con OPERATORI (es. ${invalid
        .slice(0, 2)
        .map((k) => `"${k}"`)
        .join(
          ', ',
        )}). Il logic_switch fa SOLO equality match (string === string), NON valuta espressioni. → Workflow cadrebbe SEMPRE sul fallbackBranch. SOLUZIONE: usa logic_if (vero engine condition) invece di logic_switch. Oppure pre-computa la label discreta in un agent_classifier upstream.`,
    });
  }
  return issues;
}

/**
 * Rule 4 — Branch dead-end: nodo NON terminale (i.e. il flow doveva
 * continuare) ma senza edge in uscita. Esclude i sink legittimi
 * (action_send_email, db_insert, community_*_send_message, action_http
 * notify-only).
 *
 * Severity: medium.
 */
const KNOWN_SINKS: ReadonlySet<string> = new Set([
  'action_send_email',
  'action_http',
  'db_insert',
  'db_update',
  'db_delete',
  'community_slack',
  'community_telegram',
  'community_discord',
  'community_notion',
  'community_hubspot',
  'community_salesforce',
  'community_linear',
  'community_github',
  'community_stripe',
]);

function checkDeadEnd(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  const outDegree = new Map<string, number>();
  for (const e of input.edges) outDegree.set(e.from, (outDegree.get(e.from) ?? 0) + 1);
  for (const node of input.nodes) {
    if ((outDegree.get(node.id) ?? 0) > 0) continue;
    if (KNOWN_SINKS.has(node.defId)) continue;
    if (node.defId.startsWith('trigger_')) continue; // trigger sink check separato
    // Branch logic_if/switch/extractor/classifier che termina senza out
    // = probabilmente bug (i dati spariscono).
    issues.push({
      severity: 'medium',
      code: 'DEAD_END_BRANCH',
      nodeId: node.id,
      message: `Nodo "${node.id}" (${node.defId}) non ha edges in uscita ma non è un sink noto. Il flow termina qui silenziosamente — controlla se manca un edge.`,
    });
  }
  return issues;
}

/**
 * Rule 5 — Trigger orphan: trigger_* senza edges in uscita → mai
 * eseguibile.
 *
 * Severity: critical (workflow inutile).
 */
function checkOrphanTriggers(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  const outDegree = new Map<string, number>();
  for (const e of input.edges) outDegree.set(e.from, (outDegree.get(e.from) ?? 0) + 1);
  for (const node of input.nodes) {
    if (!node.defId.startsWith('trigger_')) continue;
    if ((outDegree.get(node.id) ?? 0) === 0) {
      issues.push({
        severity: 'critical',
        code: 'ORPHAN_TRIGGER',
        nodeId: node.id,
        message: `Trigger "${node.id}" (${node.defId}) non ha edges in uscita. Il workflow non eseguirà mai nulla.`,
      });
    }
  }
  return issues;
}

/**
 * Rule 6 — Duplicate nodes: N nodi con stesso defId + stessa config
 * (escluso il campo "id"). Caso visto: 4× db_insert_audit con stesso table
 * + stessa rowJson — copy-paste laziness LLM.
 *
 * Severity: medium. Suggerimento: usare 1 nodo a valle dello switch invece
 * di N nelle branch.
 */
function checkDuplicateNodes(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  // Hash by defId + JSON(config). Skip "id" key for dedupe.
  const hashCounts = new Map<string, { ids: string[]; defId: string }>();
  for (const node of input.nodes) {
    const configHash = JSON.stringify(node.config, Object.keys(node.config).sort());
    const key = `${node.defId}|${configHash}`;
    const entry = hashCounts.get(key);
    if (entry) {
      entry.ids.push(node.id);
    } else {
      hashCounts.set(key, { ids: [node.id], defId: node.defId });
    }
  }
  for (const { ids, defId } of hashCounts.values()) {
    if (ids.length <= 1) continue;
    const firstId = ids[0] ?? '?';
    issues.push({
      severity: 'medium',
      code: 'DUPLICATE_NODES',
      nodeId: firstId,
      message: `${ids.length.toString()} nodi "${defId}" con config IDENTICA: [${ids.join(', ')}]. Probabile copy-paste laziness. Consiglio: SOSTITUIRE con UN SOLO nodo a valle dello switch (post-merge) invece di N nelle branch.`,
    });
  }
  return issues;
}

/**
 * Rule 7 — Suspicious resource IDs: rileva valori che SEMBRANO ID di
 * risorse tenant (database, email account, workspace) ma sono palesemente
 * placeholder (es. "email-account-1", "db_opportunities", "tenant-id").
 *
 * Differente da MOCK_PATTERNS perché controlla SPECIFICAMENTE i campi
 * destinati a essere ID risorsa (chiave field ~ /id|account|database|table/i)
 * e li penalizza se non sono UUID/alfanumerico hash-like.
 *
 * Severity: critical (nodo fa lookup fallito a runtime).
 */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const HASH_ID_RE = /^[A-Za-z0-9_-]{16,}$/; // tipico nanoid 21 char, ULID 26, MongoID 24

function checkSuspiciousResourceIds(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  for (const node of input.nodes) {
    for (const [field, val] of Object.entries(node.config)) {
      if (typeof val !== 'string' || val.length === 0) continue;
      // Skip se contiene template engine syntax (verrà risolto a runtime)
      if (val.includes('{{') || val.includes('$node.') || val.includes('secrets.')) continue;
      // Skip per __USE_PICKER__: marker inserito da auto-fix layer C che la
      // UI usa per forzare un dropdown pre-import. NON è ID fittizio LLM, è
      // segnaposto deterministicco — non flaggare come SUSPICIOUS.
      if (val === '__USE_PICKER__') continue;
      const isIdField =
        /^(databaseId|tableId|workspaceId|projectId|accountId|userId|tenantId|systemAccountId|botId|channelId|spaceId|orgId)$/i.test(
          field,
        ) ||
        /^(database|table|workspace|project|account|tenant|email_account|system_account)_?(id|name|key)$/i.test(
          field,
        );
      if (!isIdField) continue;
      // Valore "ID-like"? UUID o hash-id passa, altrimenti suspect
      const looksLikeRealId = UUID_RE.test(val) || HASH_ID_RE.test(val);
      // Parole sospette ANCHE dentro snake_case / kebab-case (es. "db_placeholder_xxx",
      // "email-account-1"). Match con (?:^|[_\-]) come boundary alternativo.
      const SUSPECT_WORD_RE =
        /(?:^|[_\-\s])(name|placeholder|example|sample|here|todo|fixme|test|demo|fake|mock|your|my|company|new|generic|opportunities|customers|orders|invoices|leads|account|database|table)(?:[_\-\s]|$)/i;
      const hasSuspectWord = SUSPECT_WORD_RE.test(val);
      // Pattern lazy "tipo_nome_ID" senza vero hash (es. db_opportunities = 2 parts senza alfanumerico randomico)
      const LAZY_ID_RE =
        /^(db|acc|tenant|workspace|project|user|email|smtp|imap|system|sys|table|tbl|col|field|node|wf|workflow)[_-][a-z]+(?:[_-][a-z]+)?$/i;
      const hasLazyPrefix = LAZY_ID_RE.test(val);
      if (!looksLikeRealId || hasSuspectWord || hasLazyPrefix) {
        issues.push({
          severity: 'critical',
          code: 'SUSPICIOUS_RESOURCE_ID',
          nodeId: node.id,
          field,
          message: `Campo "${field}" = "${val}" NON sembra un ID reale del tenant (atteso UUID o ID hash-like). Probabile placeholder LLM. Selezionalo via dropdown UI (db-picker / email-account-picker / workspace-picker).`,
        });
      }
    }
  }
  return issues;
}

/**
 * Entry point: applica TUTTE le rules. Ordina issues per severity
 * (critical > medium > info), poi per nodeId.
 */
// ────────────────────────────────────────────────────────────────────────────
// ARRAY_TO_SCALAR_WITHOUT_LOOP — rule #1 of the 2026-06-07 Cappella batch.
// An edge whose source emits an array (sitemap_crawler, db_query, etc.) and
// whose target consumes a scalar (seo_audit, agent_extractor, db_insert)
// MUST traverse a `logic_loop` (or other loop-body-passthrough node).
// Otherwise the consumer either crashes or applies once to the entire array.
// ────────────────────────────────────────────────────────────────────────────
function checkArrayToScalarWithoutLoop(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  const byId = new Map(input.nodes.map((n) => [n.id, n] as const));
  // Build reachability: from-set of ancestors per node. We don't recompute
  // for each edge — single BFS sufficient.
  const directIncoming = new Map<string, string[]>();
  for (const e of input.edges) {
    const list = directIncoming.get(e.to) ?? [];
    list.push(e.from);
    directIncoming.set(e.to, list);
  }

  // Walk every edge, check if the upstream path traverses a loop-body node.
  for (const edge of input.edges) {
    const fromNode = byId.get(edge.from);
    const toNode = byId.get(edge.to);
    if (!fromNode || !toNode) continue;

    if (!isArrayProducer(fromNode.defId)) continue;
    if (!isScalarConsumer(toNode.defId)) continue;

    // Walk backwards from `to` until we either reach `from` or hit a loop
    // body passthrough node. If we cross a loop body, the iteration is
    // implicit and the wiring is valid.
    if (pathHasLoopBetween(byId, directIncoming, edge.from, edge.to)) continue;

    issues.push({
      severity: 'critical',
      code: 'ARRAY_TO_SCALAR_WITHOUT_LOOP',
      nodeId: edge.to,
      message:
        `Edge "${edge.from}" (${fromNode.defId}) → "${edge.to}" (${toNode.defId}) viola lo shape ` +
        `array→scalar: l'upstream emette un array ma il downstream consuma UN elemento per esecuzione. ` +
        `Inserisci un nodo \`logic_loop\` (strategy="naive" o "batch") tra i due, in modo che il consumer ` +
        `riceva ciascun elemento dell'array singolarmente.`,
    });
  }
  return issues;
}

function pathHasLoopBetween(
  byId: ReadonlyMap<string, { id: string; defId: string }>,
  incoming: ReadonlyMap<string, readonly string[]>,
  fromId: string,
  toId: string,
): boolean {
  // BFS backwards from toId. Return true as soon as we cross a loop-body
  // passthrough node BEFORE reaching fromId. Bounded by node count to
  // avoid infinite loops on accidental cycles.
  const seen = new Set<string>();
  const stack: string[] = [toId];
  while (stack.length > 0) {
    const cur = stack.pop();
    if (cur === undefined || seen.has(cur)) continue;
    seen.add(cur);
    if (cur === fromId) continue; // reached source w/o loop
    const node = byId.get(cur);
    if (node && cur !== toId && isLoopBodyPassthrough(node.defId)) return true;
    for (const parent of incoming.get(cur) ?? []) {
      if (!seen.has(parent)) stack.push(parent);
    }
  }
  return false;
}

// ────────────────────────────────────────────────────────────────────────────
// FAN_IN_WITHOUT_MERGE — rule #4: when N edges converge on a single node,
// that node MUST be an aggregator (data_analyst, summarizer, flow_merge,
// action_aggregate). Otherwise the downstream sees a non-deterministic
// "last-arrival-wins" payload.
// ────────────────────────────────────────────────────────────────────────────
function checkFanInWithoutMerge(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  const incomingCount = new Map<string, number>();
  for (const e of input.edges) {
    incomingCount.set(e.to, (incomingCount.get(e.to) ?? 0) + 1);
  }
  for (const node of input.nodes) {
    const count = incomingCount.get(node.id) ?? 0;
    if (count < 2) continue;
    if (isAggregator(node.defId)) continue;
    // `logic_if`/`logic_switch` are also fan-in tolerant (they pick ONE branch).
    if (node.defId === 'logic_if' || node.defId === 'logic_switch' || node.defId === 'logic_join')
      continue;
    issues.push({
      severity: 'critical',
      code: 'FAN_IN_WITHOUT_MERGE',
      nodeId: node.id,
      message:
        `Nodo "${node.id}" (${node.defId}) riceve ${count.toString()} edge in entrata ma NON è un aggregator. ` +
        `I dati arriveranno in ordine non deterministico e il consumer userà solo l'ultimo payload. ` +
        `Inserisci prima un nodo \`flow_mergè o \`action_aggregatè, oppure cambia il consumer in ` +
        `\`agent_data_analyst\`/\`agent_summarizer\` per unire i risultati esplicitamente.`,
    });
  }
  return issues;
}

// ────────────────────────────────────────────────────────────────────────────
// DB_TABLE_NOT_IN_SCHEMA — rule #3 partial: db_query/db_insert/etc.
// referenziano una tabella che NON esiste nel database scelto.
// Skip se databaseId è un placeholder (__USE_PICKER__ / template).
// ────────────────────────────────────────────────────────────────────────────
const DB_NODES_WITH_TABLE: ReadonlySet<string> = new Set([
  'db_query',
  'db_insert',
  'db_insert_batch',
  'db_update',
  'db_delete',
]);
function checkDbTableNotInSchema(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  if (!input.databases || input.databases.length === 0) return issues;
  const tablesByDb = new Map<string, ReadonlySet<string>>();
  for (const db of input.databases) {
    tablesByDb.set(db.id, new Set(db.tables));
  }
  for (const node of input.nodes) {
    if (!DB_NODES_WITH_TABLE.has(node.defId)) continue;
    const dbId = typeof node.config.databaseId === 'string' ? node.config.databaseId : '';
    const table = typeof node.config.table === 'string' ? node.config.table : '';
    // Skip placeholder/expression sources — user will configure post-import.
    if (!dbId || !table) continue;
    if (dbId === '__USE_PICKER__' || dbId.includes('{{')) continue;
    // table può essere marker picker (heal pre-validation 2026-06-12: REQUIRED
    // omesso → __USE_PICKER__): la sceglie l'utente dal dropdown pre-import.
    if (table === '__USE_PICKER__' || table.includes('{{')) continue;
    const knownTables = tablesByDb.get(dbId);
    if (!knownTables) continue; // db not in tenant context (e.g. picker placeholder UUID)
    if (knownTables.has(table)) continue;
    issues.push({
      severity: 'critical',
      code: 'DB_TABLE_NOT_IN_SCHEMA',
      nodeId: node.id,
      field: 'table',
      message:
        `Nodo "${node.id}" (${node.defId}) referenzia tabella "${table}" sul database "${dbId}", ` +
        `ma quella tabella NON esiste nello schema. Tabelle disponibili: [${
          Array.from(knownTables)
            .map((t) => `"${t}"`)
            .join(', ') || '(nessuna)'
        }]. ` +
        // Il rimedio deve nominare uno strumento che chi legge POSSIEDE.
        // Fino al 2026-08-06 questo messaggio diceva soltanto «crea prima la
        // tabella via create_table»: uno strumento del percorso ad agente, che
        // nel percorso a scrittura unica NON esiste. Il modello riceveva
        // un'istruzione ineseguibile, i tentativi si consumavano tutti sullo
        // stesso muro, e l'utente vedeva il wizard fallire senza capire perché.
        `Rimedio: DICHIARA la tabella in \`tablesToCreate\` nel JSON che stai producendo ` +
        `(il server la crea prima di importare il workflow), oppure usa una tabella ` +
        `esistente. Se stai lavorando con gli strumenti, l'equivalente è \`create_table\`.`,
    });
  }
  return issues;
}

// ────────────────────────────────────────────────────────────────────────────
// CODE_NODE_LANG_MISMATCH — il campo `code` di un nodo code è scritto
// nell'ALTRO linguaggio rispetto al nodo (bug user 2026-06-09: Python dentro
// action_run_js → isolated-vm fallisce al parse). L'auto-fix Layer C §2.6
// di norma corregge il defId PRIMA del gate; questa rule è il BACKSTOP che
// rigetta i casi che l'auto-fix non ha potuto risolvere (o se bypassato).
// Critical: il nodo non sarebbe MAI eseguibile.
// ────────────────────────────────────────────────────────────────────────────
function checkCodeNodeLangMismatch(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  for (const node of input.nodes) {
    const expected = LANG_FOR_CODE_NODE.get(node.defId);
    if (!expected) continue; // non è action_run_js / action_run_python
    const codeRaw = node.config.code;
    const code = typeof codeRaw === 'string' ? codeRaw : '';
    if (code.trim().length === 0) continue;
    const detected = detectCodeLanguage(code);
    if (detected === 'ambiguous' || detected === expected) continue;
    const human = (l: string): string => (l === 'python' ? 'Python' : 'JavaScript');
    issues.push({
      severity: 'critical',
      code: 'CODE_NODE_LANG_MISMATCH',
      nodeId: node.id,
      field: 'code',
      message:
        `Nodo "${node.id}" (${node.defId}) contiene codice ${human(detected)} ma il nodo esegue ${human(expected)}. ` +
        `A runtime fallirebbe immediatamente (es. \`import\`/\`print\` non sono JavaScript valido in isolated-vm). ` +
        `SOLUZIONE: usa "${detected === 'python' ? 'action_run_python' : 'action_run_js'}" per questo codice, ` +
        `oppure riscrivi il codice in ${human(expected)}.`,
    });
  }
  return issues;
}

// ────────────────────────────────────────────────────────────────────────────
// DB_COLUMN_NOT_IN_SCHEMA — db_insert/update/delete referenziano una COLONNA
// (chiave di rowJson/whereJson/patchJson) che NON esiste nella tabella.
// Bug user 2026-06-09: db_insert rowJson={"code":…,"created_at":…} su una
// tabella con colonne [id,url,price,median_price,timestamp] → `no such column`
// + violazione NOT NULL. Il DB_TABLE check passava (la tabella esisteva), ma
// le colonne erano sbagliate. Critical.
// ────────────────────────────────────────────────────────────────────────────
const DB_COLUMN_FIELDS: Readonly<
  Record<string, { tableField: string; columnFields: readonly string[] }>
> = {
  db_insert: { tableField: 'table', columnFields: ['rowJson'] },
  db_update: { tableField: 'table', columnFields: ['whereJson', 'patchJson'] },
  db_delete: { tableField: 'table', columnFields: ['whereJson'] },
};

/**
 * Estrae i nomi-colonna referenziati da un campo key-value (rowJson, ecc.).
 * Ritorna `null` quando il valore non è un oggetto JSON parseable (→ skip
 * conservativo, niente falso-positivo). Le chiavi che sono espressioni
 * `{{...}}` vengono ignorate (non sono nomi-colonna letterali).
 */
function extractColumnKeys(raw: unknown): string[] | null {
  let obj: unknown = raw;
  if (typeof raw === 'string') {
    const trimmed = raw.trim();
    if (trimmed.length === 0) return null;
    obj = safeParseJson(trimmed);
  }
  if (!obj || typeof obj !== 'object' || Array.isArray(obj)) return null;
  return Object.keys(obj as Record<string, unknown>).filter(
    (k) => k.length > 0 && !k.includes('{{'),
  );
}

function checkDbColumnNotInSchema(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  if (!input.databases || input.databases.length === 0) return issues;
  // `${dbId}::${table}` → Set(columns)
  const columnsByDbTable = new Map<string, ReadonlySet<string>>();
  for (const db of input.databases) {
    if (!db.columns) continue;
    for (const [table, cols] of Object.entries(db.columns)) {
      columnsByDbTable.set(`${db.id}::${table}`, new Set(cols));
    }
  }
  if (columnsByDbTable.size === 0) return issues; // nessuna info colonna → skip
  for (const node of input.nodes) {
    const spec = DB_COLUMN_FIELDS[node.defId];
    if (!spec) continue;
    const dbId = typeof node.config.databaseId === 'string' ? node.config.databaseId : '';
    const table =
      typeof node.config[spec.tableField] === 'string'
        ? (node.config[spec.tableField] as string)
        : '';
    if (!dbId || !table) continue;
    if (
      dbId === '__USE_PICKER__' ||
      table === '__USE_PICKER__' ||
      dbId.includes('{{') ||
      table.includes('{{')
    )
      continue;
    const cols = columnsByDbTable.get(`${dbId}::${table}`);
    if (!cols || cols.size === 0) continue; // tabella non nel column-map → skip (table check copre l'esistenza)
    for (const field of spec.columnFields) {
      const keys = extractColumnKeys(node.config[field]);
      if (!keys || keys.length === 0) continue;
      const unknown = keys.filter((k) => !cols.has(k));
      if (unknown.length === 0) continue;
      issues.push({
        severity: 'critical',
        code: 'DB_COLUMN_NOT_IN_SCHEMA',
        nodeId: node.id,
        field,
        message:
          `Nodo "${node.id}" (${node.defId}) campo "${field}" referenzia colonne ${unknown.map((c) => `"${c}"`).join(', ')} ` +
          `che NON esistono nella tabella "${table}". Colonne disponibili: [${Array.from(cols)
            .map((c) => `"${c}"`)
            .join(', ')}]. ` +
          `A runtime: errore "no such column" (+ eventuali NOT NULL violate). Usa SOLO le colonne ` +
          `esistenti, oppure dichiara la tabella con le colonne che ti servono in \`tablesToCreate\` ` +
          `nel JSON che stai producendo. Con gli strumenti, l'equivalente è create_table/add_column.`,
      });
    }
  }
  return issues;
}

// ────────────────────────────────────────────────────────────────────────────
// OBSOLETE_MODEL — rule #6: agent_* con model id deprecato dal provider.
// Pure list-based (l'aggiornamento è un PR di una riga quando il provider
// archivia un modello). Severity medium → warning + auto-fix Layer C
// already clears il field se è obsoleto.
// ────────────────────────────────────────────────────────────────────────────
const OBSOLETE_MODELS_BY_PROVIDER: ReadonlyMap<string, ReadonlySet<string>> = new Map([
  [
    'openai',
    new Set([
      'gpt-3.5-turbo-0301',
      'gpt-3.5-turbo-0613',
      'gpt-3.5-turbo-16k-0613',
      'gpt-4-0314',
      'gpt-4-0613',
      'gpt-4-32k-0314',
      'gpt-4-32k-0613',
      'text-davinci-003',
      'text-davinci-002',
      'code-davinci-002',
    ]),
  ],
  [
    'anthropic',
    new Set([
      'claude-instant-1',
      'claude-instant-1.2',
      'claude-1',
      'claude-1.3',
      'claude-2',
      'claude-2.0',
      'claude-2.1',
      'claude-3-haiku-20240307',
      'claude-3-opus-20240229',
      'claude-3-sonnet-20240229',
    ]),
  ],
  ['gemini', new Set(['gemini-pro', 'gemini-pro-vision', 'gemini-1.0-pro'])],
  [
    'mistral',
    new Set([
      'mistral-tiny',
      'mistral-small',
      'mistral-medium', // unversioned (without -latest) deprecated 2024
    ]),
  ],
]);
function checkObsoleteModel(input: QualityGateInput): QualityIssue[] {
  const issues: QualityIssue[] = [];
  for (const node of input.nodes) {
    if (!node.defId.startsWith('agent_')) continue;
    const provider =
      typeof node.config.provider === 'string' ? node.config.provider.toLowerCase() : '';
    const model = typeof node.config.model === 'string' ? node.config.model.trim() : '';
    if (!provider || !model) continue;
    const obsolete = OBSOLETE_MODELS_BY_PROVIDER.get(provider);
    if (!obsolete?.has(model)) continue;
    issues.push({
      severity: 'medium',
      code: 'OBSOLETE_MODEL',
      nodeId: node.id,
      field: 'model',
      message:
        `Nodo "${node.id}" usa model="${model}" su provider="${provider}", che è deprecato dal vendor. ` +
        `Lascia vuoto il campo \`model\` (\`""\`) per usare il default corrente del provider, oppure aggiorna a un id supportato.`,
    });
  }
  return issues;
}

export function runQualityGate(input: QualityGateInput): QualityGateResult {
  const issues: QualityIssue[] = [
    ...checkOrphanTriggers(input),
    ...checkCircularReferences(input),
    ...checkMockPlaceholders(input),
    ...checkSuspiciousResourceIds(input),
    ...checkSwitchDefault(input),
    ...checkSwitchInvalidCaseKey(input),
    ...checkAggregationInsideLoop(input),
    ...checkDeadEnd(input),
    ...checkDuplicateNodes(input),
    ...checkArrayToScalarWithoutLoop(input),
    ...checkFanInWithoutMerge(input),
    ...checkDbTableNotInSchema(input),
    ...checkDbColumnNotInSchema(input),
    ...checkCodeNodeLangMismatch(input),
    ...checkObsoleteModel(input),
    ...runSemanticRules(input),
    // Un campo scritto senza `$node.` davanti: il nome è giusto, ma a runtime
    // vale stringa vuota e nessuno lo dice. Rifiutare qui significa che il
    // modello lo riscrive da sé, invece di consegnare il difetto all'utente.
    ...checkEspressioneNuda(input),
    // Un nodo che elabora un contenuto che non gli arriva mai: il grafo è
    // connesso e i campi ci sono, ma non c'è niente su cui lavorare.
    ...checkNienteDaElaborare(input),
    // Una condizione che non si legge vale FALSO: il ramo non parte mai, e
    // non lo dice nessuno. Rifiutare qui costa un giro di rigenerazione;
    // lasciarla passare costa un'automazione che gira a vuoto per mesi.
    ...checkRegoleCondizione(input),
    ...checkListaCheNonArriva(input),
  ];
  // Stable sort by severity rank then nodeId for deterministic output.
  const rank: Record<QualitySeverity, number> = { critical: 0, medium: 1, info: 2 };
  issues.sort((a, b) => {
    const r = rank[a.severity] - rank[b.severity];
    if (r !== 0) return r;
    return (a.nodeId ?? '').localeCompare(b.nodeId ?? '');
  });
  const shouldReject = issues.some((i) => i.severity === 'critical');
  if (issues.length > 0) {
    logger.warn(
      {
        total: issues.length,
        critical: issues.filter((i) => i.severity === 'critical').length,
        medium: issues.filter((i) => i.severity === 'medium').length,
        codes: Array.from(new Set(issues.map((i) => i.code))),
      },
      '[quality-gate] issues detected',
    );
  }
  return { ok: !shouldReject, issues, shouldReject };
}
